
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.3.0
  creationTimestamp: null
  name: clusterapplicationresourcemappings.service.binding
spec:
  group: service.binding
  names:
    kind: ClusterApplicationResourceMapping
    listKind: ClusterApplicationResourceMappingList
    plural: clusterapplicationresourcemappings
    singular: clusterapplicationresourcemapping
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: ClusterApplicationResourceMapping is the Schema for the clusterapplicationresourcemappings API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClusterApplicationResourceMappingSpec defines the desired state of ClusterApplicationResourceMapping
            properties:
              versions:
                description: Versions is the collection of versions for a given resource, with mappings.
                items:
                  description: ClusterApplicationResourceMappingVersion defines the mapping for a specific version of an application resource.
                  properties:
                    containers:
                      description: Containers is the collection of JSONPaths that container configuration may be written to.
                      items:
                        type: string
                      type: array
                    envs:
                      description: Envs is the collection of JSONPaths that env configuration may be written to.
                      items:
                        type: string
                      type: array
                    version:
                      description: Version is the version of the application resource that this mapping is for.
                      type: string
                    volumeMounts:
                      description: VolumeMounts is the collection of JSONPaths that volume mount configuration may be written to.
                      items:
                        type: string
                      type: array
                    volumes:
                      description: Volumes is the JSONPath that volume configuration must be written to.
                      type: string
                  required:
                  - version
                  - volumes
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true
    subresources: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
